### ISSUE TITLE
Exception while calling "GetResponse" in Utils.ps1

### ISSUE THREAD

**Issue by Zasch** [flofreud/posh-gvm#1]
First of all I'd like to thank you for making gvm available on windows.

I installed posh-gvm via short script method on Windows 8.1. Then I set my execution policy to unsigned and added the "Import-Module posh-gvm" to my Powershell profile. Now, when I run "gvm install groovy" I get the following error:

"Ausnahme beim Aufrufen von "GetResponse" mit 0 Argument(en):  "Die Anfrage wurde abgebrochen: Timeout für Vorgang
überschritten."
In C:\Users\Sascha\Documents\WindowsPowerShell\Modules\posh-gvm\Utils.ps1:338 Zeichen:5
-     $response = $request.GetResponse()
-     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
  - FullyQualifiedErrorId : WebException"

which translates roughly to:

"Exception while calling "GeResponse" with 0 arguments: "The request was canceled: Timeout reached."
....."

Am I doing something wrong?

**Comment by rjkmurray** [comment]
#20
