### ISSUE TITLE
posh-gvm is unable to install griffon 2.5.0

### ISSUE THREAD

**Issue by skilledindia** [flofreud/posh-gvm#12]
Hi 

posh-gvm is unable to install griffon 2.5.0

i ran gvm install griffon 2.5.0

It said version not found

**Comment by flofreud** [comment]
If you execute the the command `gvm list griffon` you will get a list of all the available griffon version. Currently this is something like the following output showing there is no 2.5.0 available via GVM / SDKMAN. 

After checking the Griffon website http://griffon-framework.org/ I think they does not distribute a SDK version anymore after release of 1.5.0. The quickstart guide recommand to use lazybones and gradle.



```
================================================================================
Available Griffon Versions
================================================================================
     1.5.0                0.3.1
     1.4.0                0.3
     1.3.0                0.2.1
     1.2.0                0.2
     1.1.0                0.1.2
     1.0.2                0.1.1
     1.0.1                0.1
     1.0.0                0.0.1
     0.9.5                0.0
     0.9.4
     0.9.3
     0.9.2
     0.9.1a
     0.9.1
     0.9

================================================================================
+ - local version
* - installed
> - currently in use
================================================================================
```
