### ISSUE TITLE
Exception calling "GetResponse" with "0" argument(s): "The operation has timed out"

### ISSUE THREAD

**Issue by jonathds** [flofreud/posh-gvm#5]
Hello I am getting this error when I send this command "gvm install groovy" - I have installed PsGet, posh-gvm, PsUrl, in my powershell ".ps1" directory:

Exception calling "GetResponse" with "0" argument(s): "The operation has timed out"
At C:\Users\jdsmith\Documents\WindowsPowerShell\Modules\posh-gvm\Utils.ps1:432 char:5
+     $response = $request.GetResponse()
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : WebException

![posh-gvm](https://cloud.githubusercontent.com/assets/11983326/7188671/84f50ac8-e447-11e4-821a-3678be3a0143.png)

**Comment by flofreud** [comment]
Hi,

could you retry again? The timeout could have been caused by a server, which was not responding, or a very slow connection. The timeout is set to 15 seconds.

I just tried and everything worked as expected.

**Comment by jonathds** [comment]
HI,

Thanks for your response,  I ran it again and received the same error.

![posh-gvm 2nd run](https://cloud.githubusercontent.com/assets/11983326/7190793/8b5eac98-e456-11e4-9d61-6a99e6d27880.png)

**Comment by flofreud** [comment]
Please try the -Verbose flag for more informations:

`gvm install groovy -Verbose`

Than try to open the link, which is shown in the Verbose output, in your browser. If this doesn't work too, the issue is probably related to your internet connection (eg. no possible route to the download source).

If it works in your browser, I have to guese. Maybe a policy issue, some other powershell module which changes something in your environment or something else. Could be really hard to debug.

**Comment by jonathds** [comment]
Thank you! So I used the -Verbose flag and pasted the url in my browser.  I was able to download the file.  I imagine that the issue is that the timeout is set too short.  The browser took a good 30 seconds at best to start the download.  May have something to with our firewalls and connection.  Is there a way to increase the time out limit?

**Comment by flofreud** [comment]
The timeout is defined around the addressed line in your error message.You could increase it from 15000 ms to 60000 ms. 

I have to think about a good solution. Im afraid that increasing the timeout would seems like an unresponding command for other user which do not expect the timeout to take 60 sec+ (if the issue would really be a unresponsive server). Maybe I could make the timeout configurable.

A start would be to handle the exception, so a solution could be propagated better.

**Comment by jonathds** [comment]
Great! Let me me start with that and go from there.  If you do find it best to make the time out configurable, please let me know.  Thanks again for all your help!

**Comment by jonathds** [comment]
So I found the Download-File function in the Utils script and changed it to 120000, that absolutely fixed the problem.
